Repository garageScript/c0d3-app, pull requests merged in 2021-04, with the labels that each got.

#608 [DNM] [Migration] Add default value for `createdAt` column
  helpers/controllers/alertController.ts
  package.json
  prisma/migrations/20210401004301_default_created_at/migration.sql
  prisma/schema.prisma
Labels: DB, dont-merge

#646 [Migration] Change user `isAdmin` column type to boolean
  __dummy__/sessionData.js
  __tests__/pages/admin/users.test.js
  __tests__/pages/profile/username.test.js
  components/AppNav.tsx
  components/admin/AdminLayout.test.js
  components/admin/AdminLayout.tsx
  components/admin/users/AdminUsersTable.test.js
  components/admin/users/AdminUsersTable.tsx
  components/admin/users/__snapshots__/AdminUsersTable.test.js.snap
  graphql/index.tsx
  graphql/queries/changeAdminRights.ts
  graphql/queryResolvers/allUsers.test.js
  graphql/typeDefs.ts
  helpers/controllers/adminController.test.js
  helpers/controllers/adminController.ts
  helpers/controllers/alertController.test.js
  helpers/controllers/challengesController.test.js
  helpers/controllers/lessonsController.test.js
  helpers/isAdmin.ts
  helpers/middleware/user.test.js
  helpers/models/User.ts
  pages/admin/users.tsx
  prisma/migrations/20210410201232_user_isAdmin_boolean/migration.sql
  prisma/schema.prisma
  stories/pages/Curriculum.stories.tsx
Labels: DB

#629 Update #545 - updates typeDefs and imports for Challenge and Submission
  __dummy__/lessonData.js
  __tests__/__snapshots__/storyshots.test.js.snap
  __tests__/pages/curriculum/[lesson].test.js
  __tests__/pages/profile/username.test.js
  __tests__/pages/review/[lesson].test.js
  components/ChallengeMaterial.test.js
  components/ChallengeMaterial.tsx
  components/LessonCard.tsx
  components/LessonTitleCard.tsx
  components/ReviewCard.tsx
  components/__snapshots__/ChallengeMaterial.test.js.snap
  components/admin/lessons/AdminLessonsSideBar.tsx
  graphql/index.tsx
  graphql/queries/acceptSubmission.ts
  graphql/queries/getSubmissions.ts
  graphql/queries/rejectSubmission.ts
  graphql/typeDefs.ts
  helpers/controllers/submissionController.ts
  helpers/hasPassedLesson.ts
  helpers/updateSubmission.ts
  pages/admin/lessons.tsx
  pages/curriculum.tsx
  pages/curriculum/[lesson].tsx
  pages/profile/[username].tsx
  pages/review/[lesson].tsx
  stories/components/ChallengeMaterial.stories.tsx
  stories/components/ChallengeQuestionCard.stories.tsx
  stories/components/ChallengeTitleCard.stories.tsx
  stories/components/LessonTitleCard.stories.tsx
  stories/components/ReviewCard.stories.tsx
  stories/pages/Curriculum.stories.tsx
  stories/profile/ProfileStarComments.stories.tsx
  stories/profile/ProfileSubmissions.stories.tsx
  stories/profile/UserProfilePage.stories.tsx
Labels: Pending
