Repository garageScript/c0d3-app, pull requests merged in 2022-09, with the labels that each got.

#2277 Add storybook-static/ to .gitignore
  .gitignore
Labels: awaiting-review

#2272 Make AdminLessonNav more generic
  __tests__/__snapshots__/storyshots.test.js.snap
  __tests__/pages/admin/lessons/[lessonSlug]/[pageName]/modules.test.js
  components/NavCard.tsx
  components/admin/lessons/AdminLessonSideNavLayout.tsx
  pages/admin/lessons/[lessonSlug]/[pageName]/index.tsx
  scss/navCard.module.scss
  stories/components/AdminLessonSideNavLayout.stories.tsx
  stories/components/NavCard.stories.tsx
Labels: awaiting-review

#2274 Remove username from AppNav
  __tests__/pages/__snapshots__/curriculum.test.js.snap
  __tests__/pages/__snapshots__/forgotpassword.test.js.snap
  __tests__/pages/admin/__snapshots__/users.test.js.snap
  __tests__/pages/admin/lessons/__snapshots__/lessons.test.js.snap
  __tests__/pages/curriculum.test.js
  __tests__/pages/curriculum/__snapshots__/[lessonSlug].test.js.snap
  __tests__/pages/profile/__snapshots__/username.test.js.snap
  __tests__/pages/review/__snapshots__/[lesson].test.js.snap
  components/ProfileDropdownMenu.test.js
  components/ProfileDropdownMenu.tsx
Labels: awaiting-review, small

#2271 fix: Button component background color
  __tests__/__snapshots__/storyshots.test.js.snap
  __tests__/pages/profile/__snapshots__/username.test.js.snap
  __tests__/pages/review/__snapshots__/[lesson].test.js.snap
  components/ChallengeMaterial/__snapshots__/ChallengeMaterial.test.js.snap
  components/__snapshots__/CopyButton.test.js.snap
  components/__snapshots__/DiffView.test.js.snap
  components/__snapshots__/ReviewCard.test.js.snap
  components/__snapshots__/SubmissionComments.test.js.snap
  components/theme/Button.tsx
  scss/button.module.scss
Labels: awaiting-review, small

#2273 fix: Submission review count shows with none submissions
  __tests__/__snapshots__/storyshots.test.js.snap
  __tests__/pages/__snapshots__/curriculum.test.js.snap
  components/LessonCard.test.js
  components/LessonCard.tsx
  components/__snapshots__/LessonCard.test.js.snap
  stories/components/LessonCard.stories.tsx
Labels: awaiting-review, small

#2265 Add DOJO exercises nav card
  __tests__/pages/exercises/[lessonSlug].test.js
  pages/exercises/[lessonSlug].tsx
Labels: awaiting-review

#2234 bug: Revert setting password from signup page
  __tests__/__snapshots__/storyshots.test.js.snap
  __tests__/pages/__snapshots__/signup.test.js.snap
  __tests__/pages/signup.test.js
  graphql/index.tsx
  graphql/queries/signupUser.ts
  graphql/resolvers/authController.test.js
  graphql/resolvers/authController.ts
  graphql/typeDefs.ts
  helpers/nextAuth.ts
  pages/signup.tsx
Labels: awaiting-review

#2284 Changing Modal components from Modal.Body to ModalBody, Modal.Header to ModalHeader, etc.
  components/SubmissionComments.tsx
Labels: bug

#2304 Bootstrap 5.2.1 Upgrade
  __tests__/__snapshots__/storyshots.test.js.snap
  __tests__/pages/profile/__snapshots__/username.test.js.snap
  __tests__/pages/review/__snapshots__/[lesson].test.js.snap
  components/ChallengeMaterial/__snapshots__/ChallengeMaterial.test.js.snap
  components/__snapshots__/CopyButton.test.js.snap
  components/__snapshots__/DiffView.test.js.snap
  components/__snapshots__/ReviewCard.test.js.snap
  components/__snapshots__/SubmissionComments.test.js.snap
  components/theme/Button.tsx
  package.json
  scss/button.module.scss
  yarn.lock
Labels: dependencies

#2306 Update Admin Lesson Page Links
  __tests__/__snapshots__/storyshots.test.js.snap
  components/admin/lessons/AdminLessonCard.test.js
  components/admin/lessons/AdminLessonCard.tsx
  components/admin/lessons/__snapshots__/AdminLessonCard.test.js.snap
Labels: enhancement

#2329 Fix buttons after bootstrap update
  __tests__/__snapshots__/storyshots.test.js.snap
  __tests__/pages/__snapshots__/_app.test.js.snap
  __tests__/pages/__snapshots__/login.test.js.snap
  __tests__/pages/__snapshots__/reset.test.js.snap
  __tests__/pages/profile/__snapshots__/username.test.js.snap
  components/AppNav/AppNav.tsx
  pages/login.tsx
  scss/appNav.module.scss
  scss/login.module.scss
Labels: bug

#2339 Discussions Card Component Design Only
  __tests__/__snapshots__/storyshots.test.js.snap
  components/DiscussionsCard/DiscussionsCard.tsx
  components/DiscussionsCard/discussionsCard.module.scss
  components/DiscussionsCard/index.tsx
  stories/components/DiscussionsCard.stories.tsx
Labels: enhancement

#2367 feat(DOJO): Create main mentor page
  __tests__/pages/curriculum/[lessonSlug]/mentor/addExercise/index.test.js
  __tests__/pages/curriculum/[lessonSlug]/mentor/index.test.js
  pages/curriculum/[lessonSlug]/mentor/addExercise/index.tsx
  pages/curriculum/[lessonSlug]/mentor/index.tsx
  pages/exercises/[lessonSlug].tsx
Labels: dont-merge
