Repository garageScript/c0d3-app, pull requests merged in 2022-05, with the labels that each got.

#1793 feat: Add Rubik font
  public/fonts/Rubik-Light.woff2
  scss/fonts.scss
Labels: enhancement

#1794 feat: Add Fira Code font
  public/fonts/FiraCode-Regular.woff2
  scss/fonts.scss
Labels: enhancement

#1809 feat(DOJO): Create module inputs component
  __tests__/__snapshots__/storyshots.test.js.snap
  components/FormCard.tsx
  components/admin/lessons/AdminLessonInputs.test.js
  components/admin/lessons/AdminModuleInputs.tsx
  scss/adminModuleInputs.module.scss
  stories/components/AdminModuleInputs.stories.tsx
Labels: enhancement

#1844 fix: `Do not assign to the variable 'module'`
  graphql/resolvers/moduleCrud.test.js
Labels: urgent

#1828 DOJO: Create Lessons side-nav component
  __tests__/__snapshots__/storyshots.test.js.snap
  components/admin/lessons/AdminLessonSideNav.test.js
  components/admin/lessons/AdminLessonSideNav.tsx
  scss/adminLessonSideNav.module.scss
  stories/components/AdminlessonSideNav.stories.tsx
Labels: enhancement, subtasks

#1811 Feat: Add text elements font styles
  scss/_text.module.scss
  scss/index.scss
Labels: enhancement

#1693 test: auto-mock next-auth in test files
  __mocks__/next-auth/nextAuthAPI.mock.ts
  __tests__/pages/login.test.js
  __tests__/pages/review/[lesson].test.js
  components/AppNav.test.js
  helpers/sessionProvider.tsx
  jest.env.js
  scss/colors.module.scss
Labels: test
